/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Services.IManageCategoryService;
import Services.IManageColorService;
import Services.IManageManufacturerService;
import Services.IManageProductDetailService;
import Services.IManageProductService;
import Services.impl.ManageCategoryService;
import Services.impl.ManageColorService;
import Services.impl.ManageManufacturerService;
import Services.impl.ManageProductDetailService;
import Services.impl.ManageProductService;
import Validation.Validator;
import ViewModels.ManageCategory;
import ViewModels.ManageColor;
import ViewModels.ManageManufacturer;
import ViewModels.ManageProduct;
import ViewModels.ManageProductDetail;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nguyen Duy Hung
 */
public class FrmManageProductDetail extends javax.swing.JFrame {

    /**
     * Creates new form FrmManageProductDetail
     */
    DefaultTableModel model;
    IManageCategoryService manageCategoryService;
    IManageColorService manageColorService;
    IManageProductService productService;
    IManageManufacturerService manufacturerService;
    IManageProductDetailService productDetailService;
    Validator validator;
    public FrmManageProductDetail() {
        initComponents();
        manageCategoryService = new ManageCategoryService();
        manageColorService = new ManageColorService();
        productService = new ManageProductService();
        productDetailService = new ManageProductDetailService();
        manufacturerService = new ManageManufacturerService();
        validator = new Validator();
        cbxCategory.setModel(new DefaultComboBoxModel(manageCategoryService.findAll().toArray()));
        cbxColor.setModel(new DefaultComboBoxModel(manageColorService.findAll().toArray()));
        cbxManufacturer.setModel(new DefaultComboBoxModel(manufacturerService.findAll().toArray()));
        cbxProduct.setModel(new DefaultComboBoxModel(productService.findAll().toArray()));
        model = (DefaultTableModel) tblProductDetail.getModel();
        loadTable();
        
        
    }
    private void loadTable(){
        model.setNumRows(0);
        List<ManageProductDetail> list = this.productDetailService.findAll();
        if(!list.isEmpty())
           for(ManageProductDetail mpd : list){
               model.addRow(new Object[]{
                   mpd.getId(),
                   mpd.getManageProduct(),
                   mpd.getManageManufacturer(),
                   mpd.getManageColor(),
                   mpd.getManageCategory(),
                   mpd.getWarrantyYear(),
                   mpd.getDecription(),
                   mpd.getQuantity(),
                   mpd.getImportPrice(),
                   mpd.getPrice()
               });
           }
    }
    private ManageProductDetail validateProductDetail(){
        ManageProduct manageProduct = (ManageProduct) cbxProduct.getSelectedItem();
        ManageColor manageColor = (ManageColor) cbxColor.getSelectedItem();
        ManageManufacturer manageManufacturer = (ManageManufacturer) cbxManufacturer.getSelectedItem();
        ManageCategory manageCategory = (ManageCategory) cbxCategory.getSelectedItem();
        int warranty = validator.getInt(txtWarranty.getText());
        String decription = validator.getString(txtDecription.getText());
        int quantity = validator.getInt(txtQuantity.getText());
        BigDecimal importPrice = validator.getBigDecimal(txtImportPrice.getText());
        BigDecimal price = validator.getBigDecimal(txtPrice.getText());
        ManageProductDetail result = new ManageProductDetail(null, manageProduct, manageCategory, manageColor, manageManufacturer, warranty, decription, quantity, importPrice, price);
        return result;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxProduct = new javax.swing.JComboBox<>();
        cbxManufacturer = new javax.swing.JComboBox<>();
        cbxColor = new javax.swing.JComboBox<>();
        cbxCategory = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtWarranty = new javax.swing.JTextField();
        txtDecription = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtImportPrice = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductDetail = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1054, 603));

        jLabel1.setText("San Pham");

        jLabel2.setText("NSX");

        jLabel3.setText("Mau Sac");

        jLabel4.setText("Dong SP");

        cbxProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxManufacturer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Nam BH");

        jLabel6.setText("Mo ta");

        jLabel7.setText("So luong ton");

        jLabel8.setText("Gia Nhap");

        jLabel9.setText("Gia Ban");

        btnAdd.setText("Them");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Sua");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Xoa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");

        tblProductDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "San Pham", "Nha San Xuat", "Mau Sac", "Dong SP", "NamBH", "Mo Ta", "So Luong Ton", "Gia Nhap", "Gia Ban"
            }
        ));
        tblProductDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductDetailMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProductDetail);
        if (tblProductDetail.getColumnModel().getColumnCount() > 0) {
            tblProductDetail.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(cbxProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cbxManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGap(65, 65, 65))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(40, 40, 40)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(37, 37, 37)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUpdate)
                                .addGap(41, 41, 41)
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReset)
                                .addGap(14, 14, 14))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDecription)
                                    .addComponent(txtWarranty)
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cbxColor, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(cbxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtImportPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 906, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(cbxProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(txtWarranty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtImportPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(txtDecription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnReset))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        ManageProductDetail manageProductDetail = this.validateProductDetail();
        if(manageProductDetail != null){
            String idInserted = this.productDetailService.insert(manageProductDetail);
            if(idInserted != null) loadTable();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblProductDetail.getSelectedRow();
        if(selectedRow != -1){
            ManageProductDetail manageProductDetail =  this.validateProductDetail();
            if(manageProductDetail != null){
                String id = (String) model.getValueAt(selectedRow, 0);
                manageProductDetail.setId(id);
                boolean updated = this.productDetailService.update(manageProductDetail);
                if(updated) loadTable();
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int[] selectedRows = tblProductDetail.getSelectedRows();
        if(selectedRows.length > 0){
            String[] ids = new String[selectedRows.length];
            for(int i = 0 ; i < selectedRows.length ; i++){
                ids[i] = (String) model.getValueAt(selectedRows[i], 0);
            }
            boolean deleted = this.productDetailService.delete(ids);
            if(deleted) loadTable();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblProductDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductDetailMouseClicked
        // TODO add your handling code here:
        int selectedRow = tblProductDetail.getSelectedRow();
        ManageProduct manageProduct = (ManageProduct) model.getValueAt(selectedRow, 1);
        ManageColor manageColor = (ManageColor) model.getValueAt(selectedRow, 3);
        ManageManufacturer manageManufacturer = (ManageManufacturer) model.getValueAt(selectedRow, 2);
        ManageCategory manageCategory = (ManageCategory) model.getValueAt(selectedRow, 4);
        String warranty =String.valueOf(model.getValueAt(selectedRow, 5));
        String decription = (String) model.getValueAt(selectedRow, 6);
        String quantity = model.getValueAt(selectedRow, 7).toString();
        String importPrice = (String) model.getValueAt(selectedRow, 8).toString();
        String price = (String) model.getValueAt(selectedRow, 9).toString();
        txtDecription.setText(decription);
        txtImportPrice.setText(importPrice);
        txtPrice.setText(price);
        txtQuantity.setText(quantity);
        txtWarranty.setText(warranty);
        cbxCategory.setSelectedItem(manageCategory);
        cbxColor.setSelectedItem(manageColor);
        cbxManufacturer.setSelectedItem(manageManufacturer);
        cbxProduct.setSelectedItem(manageProduct);
    }//GEN-LAST:event_tblProductDetailMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmManageProductDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmManageProductDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmManageProductDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmManageProductDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmManageProductDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbxCategory;
    private javax.swing.JComboBox<String> cbxColor;
    private javax.swing.JComboBox<String> cbxManufacturer;
    private javax.swing.JComboBox<String> cbxProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProductDetail;
    private javax.swing.JTextField txtDecription;
    private javax.swing.JTextField txtImportPrice;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtWarranty;
    // End of variables declaration//GEN-END:variables
}
